# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 316937cd78768561930852f8be35556bb6c1c51528d8914a3b934c72b94105d9f44d2d864107c29fa06ff1c2f713abe116072b75ad70109c73ad68ca0f4a3e09

test:
  domain_name: example.com 
  secret_key_base: 8a71445e54ea80b90fbfaffd0c4a2751b23fee77e5c72009d07a65b735e6996c133e51301258173de4c26445647d139132cb84dff439ab861e349249fb85f213

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
